plugins {
    id 'com.android.application'
}

android {
    namespace 'com.firefoxpc.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.firefoxpc.app"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release { minifyEnabled false; signingConfig signingConfigs.debug }
        debug   { debuggable true }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    aaptOptions {
        // لا تضغط هذه الأنواع — مهم لـ assets الكبيرة
        noCompress "xz", "tar", "gz", "zip", "part", "so"
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
